cleanup: missed CMO code/definitions
hmcts/fpl-ccd-configuration pull request #1640
Opened 2020-09-17 09:59 UTC by joez-f

### Change description ###

More CMO cleanup that was missed. Also cleaned up model import

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2020-09-17 10:01 UTC, lewisbirks commented on service/src/main/java/uk/gov/hmcts/reform/fpl/enums/DirectionAssignee.java
> -    public String toCustomDirectionField() {
Do we still need this one for SDO?

2020-09-17 10:20 UTC, joez-f commented on service/src/main/java/uk/gov/hmcts/reform/fpl/enums/DirectionAssignee.java
> -    public String toCustomDirectionField() {
It had 0 uses so I assume not

2020-09-17 11:18 UTC, lewisbirks requested changes
`linkToAttachedDocument` in `service/src/main/java/uk/gov/hmcts/reform/fpl/service/email/content/CaseManagementOrderEmailContentProvider.java` is no longer used

2020-09-21 10:19 UTC, lewisbirks reviewed
Looks good, couple of minor things

2020-09-21 10:19 UTC, lewisbirks commented on service/src/main/java/uk/gov/hmcts/reform/fpl/service/email/content/CaseManagementOrderEmailContentProvider.java
>  @RequiredArgsConstructor(onConstructor = @__(@Autowired))
This line is no longer required I think

2020-09-21 10:19 UTC, lewisbirks commented on service/src/main/java/uk/gov/hmcts/reform/fpl/service/email/content/CaseManagementOrderEmailContentProvider.java
>  @RequiredArgsConstructor(onConstructor = @__(@Autowired))
I don't think the logging annotation is required either

2020-09-21 10:19 UTC, lewisbirks commented on service/src/main/java/uk/gov/hmcts/reform/fpl/NotifyTemplates.java
> -    public static final String CMO_READY_FOR_PARTY_REVIEW_NOTIFICATION_TEMPLATE =
You going to deprecate the notification template in gov notify?

2020-09-21 11:08 UTC, lewisbirks approved these changes

2020-09-21 11:24 UTC, merged