refactor: application properties cleanup
hmcts/fpl-ccd-configuration pull request #2108
Opened 2021-01-18 16:18 UTC by lewisbirks

### Change description ###

Update the application properties to work with the new updates to spring boot

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-01-19 10:46 UTC, samuelzerozero requested changes

2021-01-19 10:46 UTC, samuelzerozero commented on service/src/integrationTest/java/uk/gov/hmcts/reform/fpl/controllers/ManageHearingsControllerSubmittedTest.java
> +    @MockBean
mock BankHolidaysApi instead

2021-01-19 10:46 UTC, samuelzerozero commented on service/src/integrationTest/java/uk/gov/hmcts/reform/fpl/controllers/StandardDirectionsOrderControllerAboutToSubmitTest.java
> +    private BankHolidaysService bankHolidaysService;
same here mock BankHolidaysApi

2021-01-19 18:27 UTC, lewisbirks commented on service/src/integrationTest/java/uk/gov/hmcts/reform/fpl/controllers/ManageHearingsControllerSubmittedTest.java
> +    @MockBean
done

2021-01-19 18:27 UTC, lewisbirks commented on service/src/integrationTest/java/uk/gov/hmcts/reform/fpl/controllers/StandardDirectionsOrderControllerAboutToSubmitTest.java
> +    private BankHolidaysService bankHolidaysService;
done

2021-01-20 09:05 UTC, samuelzerozero approved these changes

2021-01-20 09:26 UTC, merged