DFPL-760: Allow Child Solicitor and Barrister to upload docs
hmcts/fpl-ccd-configuration pull request #3690
Opened 2022-08-05 14:28 UTC by AlistairEdwinOsborne

https://tools.hmcts.net/jira/browse/DFPL-760

Allow child solicitor, barrister and labarrister to be able to upload documents in the manage documents flow

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-08-11 11:03 UTC, so99y commented on service/src/main/java/uk/gov/hmcts/reform/fpl/controllers/documents/ManageDocumentsController.java
> +
Is it possible to move them before line 285? And the change of line 286 will not be needed.

2022-08-11 11:10 UTC, so99y commented on service/src/integrationTest/java/uk/gov/hmcts/reform/fpl/controllers/documents/ManageDocumentsControllerSubmittedTest.java
> +        givenCaseRoles(TEST_CASE_ID, USER_ID, CaseRole.LABARRISTER);
Test case for CaseRole.BARRISTER?

2022-08-11 11:10 UTC, so99y commented on service/src/integrationTest/java/uk/gov/hmcts/reform/fpl/controllers/documents/ManageDocumentsControllerSubmittedTest.java
> +        givenCaseRoles(TEST_CASE_ID, USER_ID, CaseRole.LABARRISTER);
Test case for CaseRole.BARRISTER?

2022-08-11 11:10 UTC, so99y requested changes
please see the comments.

2022-08-17 16:04 UTC, SomeshRA approved these changes

2022-08-25 09:00 UTC, so99y commented on service/src/main/java/uk/gov/hmcts/reform/fpl/controllers/documents/ManageDocumentsController.java
>              || this.featureToggleService.isNewDocumentUploadNotificationEnabled()) {
Maybe 
```
this.featureToogleService.isNewDocumentUploadNotfiicationEnabled() || 
(!DocumentUploaderType.SOLICITOR.equals(userType)
            && !DocumentUploaderType.BARRISTER.equals(userType))
```

2022-08-25 09:16 UTC, so99y submitted a review, later dismissed
All good

2022-08-25 09:27 UTC, so99y approved these changes

2022-08-25 13:09 UTC, merged