DFPL-1037: Add 'Manage Documents' To Cafcass Login Permissions
hmcts/fpl-ccd-configuration pull request #3938
Opened 2022-11-28 15:58 UTC by qasimnawaz-moj

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DFPL-1037

### Change description ###

Add 'Manage Documents' To Cafcass Login Permissions

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-11-28 16:51 UTC, AlistairEdwinOsborne approved these changes
all good!

2022-11-28 16:58 UTC, AlistairEdwinOsborne requested changes
In response to Dan's comment, might be a good idea to double check!

2022-11-29 11:32 UTC, DanCatchpole requested changes
Think caseworker-publiclaw-cafcass needs to be added to AuthorisationCaseEvent too

2022-11-29 11:40 UTC, DanCatchpole commented on ccd-definition/AuthorisationCaseEvent/CareSupervision/AuthorisationCaseEvent.json
> -          "caseworker-publiclaw-gatekeeper"
think they only need access to this event (the others are specifically for LAs + solicitors to be restricted to certain types of docs I believe

2022-11-29 12:00 UTC, DanCatchpole approved these changes
think it all looks good! I imagine if there's a missing field anywhere the QAs will spot that quicker than I can 🤣

2022-12-15 13:55 UTC, DanCatchpole submitted a review, later dismissed

2023-01-11 13:59 UTC, merged