DFPL-1401 INC5501195 Manage Cases/CCD Not creating orders
hmcts/fpl-ccd-configuration pull request #4384
Opened 2023-05-04 14:40 UTC by so99y

### JIRA link (if applicable) ###
 https://tools.hmcts.net/jira/browse/DFPL-1401

### Change description ###
- create a migration script to add back `relatingLA` for a standalone application.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-05-04 15:22 UTC, AlistairEdwinOsborne requested changes

2023-05-04 15:22 UTC, AlistairEdwinOsborne commented on service/src/main/java/uk/gov/hmcts/reform/fpl/controllers/support/MigrateCaseController.java
> +        "DFPL-1380", this::run1380,
did you mean to re-include 1380 instead of 1303?

2023-05-04 15:23 UTC, AlistairEdwinOsborne commented on service/src/main/java/uk/gov/hmcts/reform/fpl/controllers/support/MigrateCaseController.java
> +        "DFPL-1380", this::run1380,
nevermind ignore this, I got confused a I thought it would be more than 1 migration!

2023-05-09 16:07 UTC, so99y commented
Depends on DFPL-1427

2023-05-22 10:57 UTC, merged