DFPL-2140 Upload Documents
hmcts/fpl-ccd-configuration pull request #5203
Opened 2024-03-21 16:27 UTC by Braimah101

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DFPL-2140

### Change description ###

Objective: Extend the smoke test coverage by introducing a dedicated section to assess the functionality and reliability of the document upload feature within the application.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2024-03-21 16:44 UTC, Iphiclus requested changes
I believe this has already been added with AddApplicationDocuments page and ticket: https://tools.hmcts.net/jira/browse/DFPL-2150
But I might be wrong?

2024-03-21 16:44 UTC, Iphiclus commented on playwright-e2e/fixtures/create-fixture.ts
> +import { UploadDocuments } from "../pages/upload-documents";
I believe this has already been added with AddApplicationDocuments page and ticket: https://tools.hmcts.net/jira/browse/DFPL-2150

2024-03-21 16:44 UTC, Iphiclus commented on playwright-e2e/pages/start-application.ts
> +  uploadDocumentsHasBeenUpdated() {
Hi, Is this needed?

2024-03-21 16:44 UTC, Iphiclus commented on playwright-e2e/pages/start-application.ts
> +
Hi, is this newline needed?

2024-03-21 16:44 UTC, Iphiclus commented on playwright-e2e/pages/upload-documents.ts
> +
Hi, are these newlines needed?

2024-03-21 16:44 UTC, Iphiclus commented on playwright-e2e/tests/smoke-test.spec.ts
> +  // // Orders and directions sought
Hi are the double double backslashes needed?

2024-03-21 16:44 UTC, Iphiclus commented on playwright-e2e/tests/smoke-test.spec.ts
> +  // // Hearing urgency
Hi are the double double backslashes needed?

2024-03-21 16:44 UTC, Iphiclus commented on playwright-e2e/tests/smoke-test.spec.ts
> +  // // Grounds for the application
Hi are the double double backslashes needed?

2024-03-21 16:44 UTC, Iphiclus commented on playwright-e2e/tests/smoke-test.spec.ts
> +  // // Add respondents' details
Hi are the double double backslashes needed?

2024-03-21 16:44 UTC, Iphiclus commented on playwright-e2e/tests/smoke-test.spec.ts
> +
Hi, is this newline needed?

2024-11-21 09:27 UTC, closed without merging

2024-11-21 09:27 UTC, DanCatchpole commented
ticket was withdrawn