DFPL-2241 Court services needed - smoke test enhancement
hmcts/fpl-ccd-configuration pull request #5283
Opened 2024-04-19 13:58 UTC by Braimah101

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DFPL-2241

### Change description ###
As part of the FPL, we need to create a  case to the new Playwright framework. This task involves migrating the test suite and updating any necessary configurations and tests as required.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2024-04-24 09:26 UTC, chak-shing-lo-justice submitted a review, later dismissed
lgtm

2024-04-29 12:04 UTC, qasimnawaz-moj approved these changes
lgtm

2024-04-30 09:41 UTC, abigailsmith97 requested changes

2024-04-30 09:41 UTC, abigailsmith97 commented on playwright-e2e/pages/start-application.ts
missing '}'

2024-04-30 09:45 UTC, Braimah101 commented on playwright-e2e/pages/start-application.ts
Done

2024-05-01 14:31 UTC, DanCatchpole approved these changes
lgtm!

2024-05-03 08:25 UTC, merged